### ISSUE TITLE
Allowed values from RegEx pattern

### ISSUE THREAD

**Issue by brandonb927** [scottmcginness/eslint-plugin-tags-validator#1]
First off, thank you for building this plugin! I was attempting to do this myself before I realized I am not a someone who understands the ESLint AST to build resilient rules 😅

I am wondering if there would be a way to allow a RegEx pattern to be used for the allowedValues key, or something like that. I ask because we are implementing a method in which certain teams in our organization are responsible for certain tagged tests with `team_*` tagging, but I want to enforce linting to verify that all `describe` blocks contain a valid "team tag". This would also bne useful for other patterns that we use, but supporting this use-case would be a big win for us!

**Comment by brandonb927** [comment]
Something like the following would be a good example of the rule definition:
```
'tags-validator/must-match': ['error', { pattern: 'regex pattern' }]
```

**Comment by scottmcginness** [comment]
Thank you!
This is a fine idea and shouldn't be too hard to implement.

The name `pattern` makes sense to me. I'll take a look at adding that as a separate option, rather than mixing `RegExp` with the current `allowedValues`.

**Comment by scottmcginness** [comment]
I've pushed this into a new version `1.5.0`. Should work just as you've got above ([doc example](https://github.com/scottmcginness/eslint-plugin-tags-validator/?tab=readme-ov-file#3-pattern-values)).

Thanks again for the suggestion

**Comment by brandonb927** [comment]
Thank you for incorporating my feedback! I appreciate it immensely, and I think this can be closed now.
